[tool.poetry]
name = "kwork"
version = "0.0.3"
description = "simple async wrapper for kwork.ru"
authors = ["kesha1225"]

[tool.poetry.dependencies]
python = "^3.7"
aiohttp = "^3.6.2"
pydantic = "^1.4"
websockets = "^9.1"

[tool.poetry.dev-dependencies]
pytest = "^5.2"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
